# Generated by Django 6.0.3 on 2026-04-28 08:49

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_CATEGORIES = [
    'Plastic Waste',
    'Organic Waste',
    'E-Waste',
    'Medical Waste',
    'Glass Waste',
    'Metal Waste',
    'Paper Waste',
    'Construction Waste',
    'Hazardous Waste',
    'Textile Waste',
    'Food Waste',
    'Battery Waste',
    'Electronic Appliances',
    'Industrial Waste',
    'Garden Waste',
]


def seed_and_backfill(apps, schema_editor):
    WasteCategory = apps.get_model('waste_app', 'WasteCategory')
    Complaint = apps.get_model('waste_app', 'Complaint')

    for name in DEFAULT_CATEGORIES:
        WasteCategory.objects.get_or_create(name=name)

    categories = {c.name.lower(): c for c in WasteCategory.objects.all()}

    for complaint in Complaint.objects.all():
        raw_name = (complaint.waste_type_text or '').strip()
        if not raw_name:
            raw_name = 'Organic Waste'

        key = raw_name.lower()
        category = categories.get(key)
        if category is None:
            category, _ = WasteCategory.objects.get_or_create(name=raw_name)
            categories[category.name.lower()] = category

        complaint.waste_type = category
        complaint.save(update_fields=['waste_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('waste_app', '0002_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste_app.recyclingcenter')),
                ('default_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste_app.worker')),
            ],
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='waste_type',
            new_name='waste_type_text',
        ),
        migrations.AddField(
            model_name='complaint',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste_app.wastecategory'),
        ),
        migrations.RunPython(seed_and_backfill, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='complaint',
            name='waste_type_text',
        ),
    ]
