# Generated by Django 6.0.3 on 2026-04-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_app', '0003_wastecategory_alter_complaint_waste_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
